### ISSUE TITLE
Clarification on logX functions.

### ISSUE THREAD

**Issue by locallycompact** [AJChapman/co-log-polysemy-formatting#1]
Hi. First of all thanks for the library.

I'm struggling to understand the why the logX functions are arranged in the way that they are. I'll set up an example.

```
data FSExist m a where
  DoesFileExist :: Path b File -> FSExist m Bool
  DoesDirExist  :: Path b Dir  -> FSExist m Bool

makeSem ''FSExist
```

Then I want to intercept to add logging, but only with a tracer type so as to not commit to any severity or message.

```
data FileExists where
  FileExists    :: Path b File -> FileExists
  FileNotExists :: Path b File -> FileExists

logFileExists :: Members '[FSExist, Log FileExists] r => Sem r a -> Sem r a
logFileExists = intercept \case
  DoesFileExist x -> do
    z <- doesFileExist x
    case z of
      True  -> log $ FileExists x
      False -> log $ FileNotExists x
    return z
  DoesDirExist x -> doesDirExist x
```

Now that I have this, my intuition would be to do something like this:

```
mapLog :: forall k x r a. Members '[Log x] r => (k -> x) -> Sem (Log k ': r) a -> Sem r a
mapLog f = interpret $ \(Log x) -> log (f x)

mapLogInfo :: forall k x r a. Members '[Log (Msg Severity)] r => (k -> Text) -> Sem (Log k ': r) a -> Sem r a
mapLogInfo f = interpret $ \(Log x) -> logInfo $ T.unpack $ f x

path :: Format r (Path b t -> r)
path = fmap (. toFilePathText) stext

fileExistsLogText :: FileExists -> Text
fileExistsLogText = \case
  FileExists f    -> sformat ("File " % path % " found in filesystem.") f
  FileNotExists f -> sformat ("File " % path % " not found in filesystem.") f
```

Then I would be able to `mapLogInfo @FileExists fileExistsLogText` at the point where it's relevant, but this isn't how `logInfo` is set up. What is the idiomatic way to do this?

**Comment by AJChapman** [comment]
Hi, I'm glad to hear someone is using it!

The intended use of logInfo is a lot simpler than what you are describing. It's designed to make the simple case very easy, and perhaps this means that your complex case is even more complex. So my equivalent of your example would be something like:

```haskell
checkFileExists
  :: ( WithLog r
     , Member (Error FileNotFoundError) r
    )
  => FilePath -> Sem r ()
checkFileExists f =
  if doesFileExist f
    then do
      logInfo ("Found file '" % string %"'") f
      pure ()
    else do
      logError ("File not found: '" % string % "'") f
      throw $ FileNotFoundError f
```

Though I'm probably missing some of why you're making an effect for this.

Re-reading your code, it looks like you just want to replace your `logInfo $ T.unpack` with `logInfo stext`? But I'm tired and typing on a phone, so I'll take another look tomorrow.

**Comment by locallycompact** [comment]
I'm trying to follow the principle laid out in this video of tracing only typed values at the call site. https://youtu.be/qzOQOmmkKEM?t=1379

This just allows me to apply the tracer at every call site for that effect. Maybe intercepting every effect is a bit pathological, but the problem of transforming the tracer into a log message is the important part.

**Comment by AJChapman** [comment]
Thanks for the link, that looks like a cool technique. I'd like to explore that idea some time, but I haven't got any good advice for you right now. Maybe create a topic on https://funprog.zulipchat.com/#narrow/stream/216942-Polysemy . The people there are very helpful and know a lot more about Polysemy techniques than me. For a start though, you could look at the Trace effect: https://hackage.haskell.org/package/polysemy-1.3.0.0/docs/Polysemy-Trace.html

As for why the log functions are the way they are, this library is really just intended to be a traditional log-at-the-event-site kind of library, so they are set up for doing this. Actually, in the video you linked, the example of this kind of logging uses `formatting` with a `logInfo` that takes a strict `Text`, so each call looks like `logInfo $ sformat _`. But in `co-log-polysemy-formatting`, `logInfo` takes a formatter, not a `Text`, so your logging calls can be a bit shorter.

**Comment by AJChapman** [comment]
I've taken further discussion of this to https://funprog.zulipchat.com/#narrow/stream/216942-Polysemy/topic/Contravariant.20logging
